var annotated_dup =
[
    [ "doctest", null, [
      [ "detail", null, [
        [ "types", null, [
          [ "enable_if", "structdoctest_1_1detail_1_1types_1_1enable__if.html", null ],
          [ "enable_if&lt; true, T &gt;", "structdoctest_1_1detail_1_1types_1_1enable__if_3_01true_00_01_t_01_4.html", null ],
          [ "true_type", "structdoctest_1_1detail_1_1types_1_1true__type.html", null ],
          [ "false_type", "structdoctest_1_1detail_1_1types_1_1false__type.html", null ],
          [ "remove_reference", "structdoctest_1_1detail_1_1types_1_1remove__reference.html", null ],
          [ "remove_reference&lt; T &amp; &gt;", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01_t_01_6_01_4.html", null ],
          [ "remove_reference&lt; T &amp;&amp; &gt;", "structdoctest_1_1detail_1_1types_1_1remove__reference_3_01_t_01_6_6_01_4.html", null ],
          [ "is_same", "structdoctest_1_1detail_1_1types_1_1is__same.html", null ],
          [ "is_same&lt; T, T &gt;", "structdoctest_1_1detail_1_1types_1_1is__same_3_01_t_00_01_t_01_4.html", null ],
          [ "is_rvalue_reference", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference.html", null ],
          [ "is_rvalue_reference&lt; T &amp;&amp; &gt;", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference_3_01_t_01_6_6_01_4.html", null ],
          [ "remove_const", "structdoctest_1_1detail_1_1types_1_1remove__const.html", null ],
          [ "remove_const&lt; const T &gt;", "structdoctest_1_1detail_1_1types_1_1remove__const_3_01const_01_t_01_4.html", null ],
          [ "is_enum", "structdoctest_1_1detail_1_1types_1_1is__enum.html", null ],
          [ "underlying_type", "structdoctest_1_1detail_1_1types_1_1underlying__type.html", null ],
          [ "is_pointer", "structdoctest_1_1detail_1_1types_1_1is__pointer.html", null ],
          [ "is_pointer&lt; T * &gt;", "structdoctest_1_1detail_1_1types_1_1is__pointer_3_01_t_01_5_01_4.html", null ],
          [ "is_array", "structdoctest_1_1detail_1_1types_1_1is__array.html", null ],
          [ "is_array&lt; T[SIZE]&gt;", "structdoctest_1_1detail_1_1types_1_1is__array_3_01_t_0f_s_i_z_e_0e_4.html", null ]
        ] ],
        [ "deferred_false", "structdoctest_1_1detail_1_1deferred__false.html", null ],
        [ "is_std_string", "structdoctest_1_1detail_1_1is__std__string.html", null ],
        [ "is_std_string&lt; T, typename types::enable_if&lt; types::is_same&lt; decltype(declval&lt; const T &amp; &gt;().c_str()), const char * &gt;::value &amp;&amp;types::is_same&lt; decltype(declval&lt; const T &amp; &gt;().size()), size_t &gt;::value &gt;::type &gt;", "structdoctest_1_1detail_1_1is__std__string_3_01_t_00_01typename_01types_1_1enable__if_3_01types_2de037c573a46121f59eca8f5b5a731f.html", null ],
        [ "has_insertion_operator", "structdoctest_1_1detail_1_1has__insertion__operator.html", null ],
        [ "has_insertion_operator&lt; T, decltype(operator&lt;&lt;(declval&lt; std::ostream &amp; &gt;(), declval&lt; const T &amp; &gt;()), void())&gt;", "structdoctest_1_1detail_1_1has__insertion__operator_3_01_t_00_01decltype_07operator_3_3_07declvab094f732977dc5a8a6181e0b8269a776.html", null ],
        [ "should_stringify_as_underlying_type", "structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html", null ],
        [ "is_pair", "structdoctest_1_1detail_1_1is__pair.html", null ],
        [ "is_pair&lt; T, types::void_t&lt; typename T::first_type, typename T::second_type, decltype(declval&lt; T &gt;().first), decltype(declval&lt; T &gt;().second)&gt; &gt;", "structdoctest_1_1detail_1_1is__pair_3_01_t_00_01types_1_1void__t_3_01typename_01_t_1_1first__typ97ed414dfe36750d42ae446dcf1a18f4.html", null ],
        [ "is_container", "structdoctest_1_1detail_1_1is__container.html", null ],
        [ "is_container&lt; T, types::void_t&lt; typename T::value_type, typename T::iterator, decltype(declval&lt; T &gt;().begin()), decltype(declval&lt; T &gt;().end())&gt; &gt;", "structdoctest_1_1detail_1_1is__container_3_01_t_00_01types_1_1void__t_3_01typename_01_t_1_1valueb97f805f821edcbb0eec78032ce8a7ca.html", null ],
        [ "StringMakerBase", "structdoctest_1_1detail_1_1_string_maker_base.html", null ],
        [ "filldata", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "StringMakerBase&lt; true &gt;", "structdoctest_1_1detail_1_1_string_maker_base_3_01true_01_4.html", null ],
        [ "filldata&lt; T[N]&gt;", "structdoctest_1_1detail_1_1filldata_3_01_t_0f_n_0e_4.html", null ],
        [ "filldata&lt; const char[N]&gt;", "structdoctest_1_1detail_1_1filldata_3_01const_01char_0f_n_0e_4.html", null ],
        [ "filldata&lt; const void * &gt;", "structdoctest_1_1detail_1_1filldata_3_01const_01void_01_5_01_4.html", null ],
        [ "filldata&lt; const volatile void * &gt;", "structdoctest_1_1detail_1_1filldata_3_01const_01volatile_01void_01_5_01_4.html", null ],
        [ "filldata&lt; T * &gt;", "structdoctest_1_1detail_1_1filldata_3_01_t_01_5_01_4.html", null ],
        [ "filldata&lt; T, typename detail::types::enable_if&lt;!detail::has_insertion_operator&lt; T &gt;::value &amp;&amp;detail::is_pair&lt; T &gt;::value &gt;::type &gt;", "structdoctest_1_1detail_1_1filldata_3_01_t_00_01typename_01detail_1_1types_1_1enable__if_3_9detaa8666b81badacc32033ad72bded95b8c.html", null ],
        [ "filldata&lt; T, typename detail::types::enable_if&lt; !detail::has_insertion_operator&lt; T &gt;::value &amp;&amp;detail::is_container&lt; T &gt;::value &gt;::type &gt;", "structdoctest_1_1detail_1_1filldata_3_01_t_00_01typename_01detail_1_1types_1_1enable__if_3_01_9d9dcd4a078e0a95b0118a6aa265dbba06.html", null ],
        [ "RelationalComparator", "structdoctest_1_1detail_1_1_relational_comparator.html", null ],
        [ "Result", "structdoctest_1_1detail_1_1_result.html", null ],
        [ "ResultBuilder", "structdoctest_1_1detail_1_1_result_builder.html", null ],
        [ "Expression_lhs", "structdoctest_1_1detail_1_1_expression__lhs.html", null ],
        [ "ExpressionDecomposer", "structdoctest_1_1detail_1_1_expression_decomposer.html", null ],
        [ "Subcase", "structdoctest_1_1detail_1_1_subcase.html", null ],
        [ "TestSuite", "structdoctest_1_1detail_1_1_test_suite.html", null ],
        [ "TestCase", "structdoctest_1_1detail_1_1_test_case.html", null ],
        [ "IExceptionTranslator", "structdoctest_1_1detail_1_1_i_exception_translator.html", null ],
        [ "ExceptionTranslator", "classdoctest_1_1detail_1_1_exception_translator.html", null ],
        [ "ContextScopeBase", "structdoctest_1_1detail_1_1_context_scope_base.html", null ],
        [ "ContextScope", "classdoctest_1_1detail_1_1_context_scope.html", null ],
        [ "MessageBuilder", "structdoctest_1_1detail_1_1_message_builder.html", null ],
        [ "TestFailureException", "structdoctest_1_1detail_1_1_test_failure_exception.html", null ]
      ] ],
      [ "String", "classdoctest_1_1_string.html", null ],
      [ "StringMaker", "structdoctest_1_1_string_maker.html", null ],
      [ "Contains", "classdoctest_1_1_contains.html", null ],
      [ "Approx", "structdoctest_1_1_approx.html", null ],
      [ "IsNaN", "structdoctest_1_1_is_na_n.html", null ],
      [ "ContextOptions", "structdoctest_1_1_context_options.html", null ],
      [ "AssertData", "structdoctest_1_1_assert_data.html", "structdoctest_1_1_assert_data" ],
      [ "SubcaseSignature", "structdoctest_1_1_subcase_signature.html", null ],
      [ "TestCaseData", "structdoctest_1_1_test_case_data.html", null ],
      [ "IContextScope", "structdoctest_1_1_i_context_scope.html", null ],
      [ "MessageData", "structdoctest_1_1_message_data.html", null ],
      [ "Context", "classdoctest_1_1_context.html", null ],
      [ "CurrentTestCaseStats", "structdoctest_1_1_current_test_case_stats.html", null ],
      [ "TestCaseException", "structdoctest_1_1_test_case_exception.html", null ],
      [ "TestRunStats", "structdoctest_1_1_test_run_stats.html", null ],
      [ "QueryData", "structdoctest_1_1_query_data.html", null ],
      [ "IReporter", "structdoctest_1_1_i_reporter.html", null ]
    ] ],
    [ "std", null, [
      [ "char_traits", "structstd_1_1char__traits.html", null ],
      [ "basic_ostream", "classstd_1_1basic__ostream.html", null ],
      [ "basic_istream", "classstd_1_1basic__istream.html", null ],
      [ "tuple", "classstd_1_1tuple.html", null ]
    ] ]
];